master:
  image: frosner/spark-node
  environment:
    ID: dlv
    SPARK_ROLE: spark-master
  ports:
    - "8080"
  expose:
    - "7077"
slave:
  image: frosner/spark-node
  links:
    - master
  environment:
    ID: dlv
    SPARK_ROLE: spark-slave
zeppelin:
  image: frosner/zeppelin
  links:
    - master
  environment:
    ID: dlv
  ports:
    - "8080"
    - "4040"
  volumes:
    - ./notebooks:/usr/local/zeppelin/notebooks
