master:
  image: frosner/spark
  environment:
    ID: dlv
    SPARK_ROLE: spark-master
  ports:
    - 20000:8080
  expose:
    - "7077"
slave:
  image: frosner/spark
  links:
    - master
  environment:
    ID: dlv
    SPARK_ROLE: spark-slave
zeppelin:
  image: frosner/zeppelin
  links:
    - master
  environment:
    ID: dlv
  ports:
    - 20001:8080
    - 20002:4040
  volumes:
    - ./notebooks:/usr/local/zeppelin/notebooks
